// src/routes/queries/+page.svelte
<script lang="ts">
	import { Button, Badge } from '$lib/ui';
	import { Plus } from 'lucide-svelte';
	import { useQueries, useCreateQuery, useSetQueryStatus } from '$features/queries/queries';
	import { STAGE_BY_STATUS, nextStatus } from '$features/queries/workflow';
	import { formatAmount } from '$lib/money';

	const queries = useQueries();
	const createQuery = useCreateQuery();
	const setStatus = useSetQueryStatus();

	let showForm = $state(false);
	let form = $state({ client_name: '', client_phone: '', destination: '' });

	async function submit(e: SubmitEvent) {
		e.preventDefault();
		await $createQuery.mutateAsync({ ...form });
		form = { client_name: '', client_phone: '', destination: '' };
		showForm = false;
	}
</script>

<div class="mb-6 flex items-center justify-between">
	<div>
		<h1 class="text-2xl font-bold text-slate-800">Queries</h1>
		<p class="text-sm text-slate-500">The 10-stage booking pipeline.</p>
	</div>
	<Button onclick={() => (showForm = !showForm)}>
		<Plus class="h-4 w-4" /> New Query
	</Button>
</div>

{#if showForm}
	<form
		onsubmit={submit}
		class="mb-6 grid grid-cols-1 gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-4"
	>
		<input
			placeholder="Client name"
			bind:value={form.client_name}
			required
			class="rounded-lg border border-slate-300 px-3 py-2 text-sm"
		/>
		<input
			placeholder="Phone"
			bind:value={form.client_phone}
			required
			class="rounded-lg border border-slate-300 px-3 py-2 text-sm"
		/>
		<input
			placeholder="Destination"
			bind:value={form.destination}
			required
			class="rounded-lg border border-slate-300 px-3 py-2 text-sm"
		/>
		<Button type="submit" disabled={$createQuery.isPending}>
			{$createQuery.isPending ? 'Saving…' : 'Create'}
		</Button>
	</form>
{/if}

{#if $queries.isLoading}
	<p class="text-slate-400">Loading…</p>
{:else if $queries.isError}
	<p class="text-red-600">Failed to load: {$queries.error.message}</p>
{:else if ($queries.data ?? []).length === 0}
	<div class="rounded-xl border border-dashed border-slate-300 p-10 text-center text-slate-400">
		No queries yet. Create your first one to start the season.
	</div>
{:else}
	<div class="overflow-hidden rounded-xl border border-slate-200 bg-white">
		<table class="w-full text-sm">
			<thead class="border-b border-slate-100 bg-slate-50 text-left text-xs uppercase text-slate-400">
				<tr>
					<th class="px-4 py-3 font-medium">Query</th>
					<th class="px-4 py-3 font-medium">Client</th>
					<th class="px-4 py-3 font-medium">Destination</th>
					<th class="px-4 py-3 font-medium">Stage</th>
					<th class="px-4 py-3 text-right font-medium">Selling</th>
					<th class="px-4 py-3 text-right font-medium">Profit</th>
					<th class="px-4 py-3"></th>
				</tr>
			</thead>
			<tbody class="divide-y divide-slate-50">
				{#each $queries.data ?? [] as q (q.id)}
					{@const next = nextStatus(q.status)}
					<tr class="hover:bg-slate-50">
						<td class="px-4 py-3 font-mono text-xs">
							<a href="/queries/{q.id}" class="text-brand-600 hover:underline">{q.query_number}</a>
						</td>
						<td class="px-4 py-3 font-medium text-slate-700">
							<a href="/queries/{q.id}" class="hover:text-brand-600">{q.client_name}</a>
						</td>
						<td class="px-4 py-3 text-slate-600">{q.destination}</td>
						<td class="px-4 py-3">
							<Badge tone={STAGE_BY_STATUS[q.status].tone}>{STAGE_BY_STATUS[q.status].label}</Badge>
						</td>
						<td class="px-4 py-3 text-right text-slate-700">{formatAmount(Number(q.selling_price))}</td>
						<td class="px-4 py-3 text-right font-medium text-green-600">{formatAmount(Number(q.profit))}</td>
						<td class="px-4 py-3 text-right">
							{#if next}
								<Button
									variant="secondary"
									size="sm"
									disabled={$setStatus.isPending}
									onclick={() => $setStatus.mutate({ id: q.id, status: next })}
								>
									→ {STAGE_BY_STATUS[next].label}
								</Button>
							{/if}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
{/if}

// nextjs-app/src/app/queries/page.tsx
'use client';

import { useEffect, useState, FormEvent } from 'react';
import Navbar from '@/components/Navbar';
import { Plus, X } from 'lucide-react';

interface Query {
  id: number;
  query_number: string;
  passenger_name: string;
  phone: string;
  email: string | null;
  travel_type: string;
  status: string;
  created_at: string;
}

export default function QueriesPage() {
  const [queries, setQueries] = useState<Query[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [formData, setFormData] = useState({
    passenger_name: '',
    phone: '',
    email: '',
    travel_type: 'Umrah'
  });

  useEffect(() => {
    fetchQueries();
  }, []);

  const fetchQueries = async () => {
    try {
      const response = await fetch('/api/queries');
      const data = await response.json();
      if (data.success) {
        setQueries(data.data);
      }
    } catch (error) {
      console.error('Failed to fetch queries:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    try {
      const response = await fetch('/api/queries', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (data.success) {
        setShowModal(false);
        setFormData({
          passenger_name: '',
          phone: '',
          email: '',
          travel_type: 'Umrah'
        });
        fetchQueries();
      }
    } catch (error) {
      console.error('Failed to create query:', error);
    }
  };

  const updateStatus = async (id: number, status: string) => {
    try {
      const response = await fetch(`/api/queries/${id}/status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status }),
      });

      if (response.ok) {
        fetchQueries();
      }
    } catch (error) {
      console.error('Failed to update status:', error);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="flex items-center justify-center h-96">
          <div className="text-gray-500">Loading...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex items-center justify-between mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Queries</h1>
          <button
            onClick={() => setShowModal(true)}
            className="btn btn-primary flex items-center space-x-2"
          >
            <Plus size={20} />
            <span>New Query</span>
          </button>
        </div>

        {/* Queries Table */}
        <div className="card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Query #
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Passenger
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Contact
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Travel Type
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {queries.map((query) => (
                  <tr key={query.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {query.query_number}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">{query.passenger_name}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-900">{query.phone}</div>
                      {query.email && <div className="text-sm text-gray-500">{query.email}</div>}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-primary-100 text-primary-800">
                        {query.travel_type}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <select
                        value={query.status}
                        onChange={(e) => updateStatus(query.id, e.target.value)}
                        className={`text-xs font-medium rounded px-2 py-1 border-0 ${
                          query.status === 'New' ? 'bg-blue-100 text-blue-800' :
                          query.status === 'Working' ? 'bg-yellow-100 text-yellow-800' :
                          query.status === 'Quoted' ? 'bg-purple-100 text-purple-800' :
                          query.status === 'Finalized' ? 'bg-green-100 text-green-800' :
                          'bg-red-100 text-red-800'
                        }`}
                      >
                        <option value="New">New</option>
                        <option value="Working">Working</option>
                        <option value="Quoted">Quoted</option>
                        <option value="Finalized">Finalized</option>
                        <option value="Cancelled">Cancelled</option>
                      </select>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Create Query Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4">
            <div className="flex items-center justify-between p-6 border-b">
              <h2 className="text-xl font-semibold text-gray-900">Create New Query</h2>
              <button
                onClick={() => setShowModal(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <X size={24} />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Passenger Name
                </label>
                <input
                  type="text"
                  value={formData.passenger_name}
                  onChange={(e) => setFormData({ ...formData, passenger_name: e.target.value })}
                  className="input"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Phone
                </label>
                <input
                  type="tel"
                  value={formData.phone}
                  onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                  className="input"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Email (Optional)
                </label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  className="input"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Travel Type
                </label>
                <select
                  value={formData.travel_type}
                  onChange={(e) => setFormData({ ...formData, travel_type: e.target.value })}
                  className="input"
                  required
                >
                  <option value="Umrah">Umrah</option>
                  <option value="Malaysia">Malaysia</option>
                  <option value="Flight">Flight Only</option>
                  <option value="Hotel">Hotel Only</option>
                  <option value="Other">Other</option>
                </select>
              </div>

              <div className="flex space-x-3 pt-4">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="btn btn-secondary flex-1"
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary flex-1">
                  Create Query
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
